name: 'api'

on:
  push:
    branches: ['main']
    paths: src/ToggleOn.Api
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true

env:
  AZURE_WEBAPP_NAME: app-toggleon-api                 # set this to the name of your Azure Web App
  AZURE_WEBAPP_PACKAGE_PATH: '.'                      # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x'                             # set this to the .NET Core version to use
  PROJECT_PATH: 'src/ToggleOn.Api'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Set up dependency caching for faster builds
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ${{ env.PROJECT_PATH }}

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/publish
        working-directory: ${{ env.PROJECT_PATH }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: api
          path: ${{env.DOTNET_ROOT}}/publish

  
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: api

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Deploy Api
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ format('{0}-{1}', env.AZURE_WEBAPP_NAME, inputs.environment) }}
          #publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

